### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by jay-jlm** [Dorthu/2019-christmas-adventure#1]
Hi, 

Congrats on your game, it looks pretty cool so far.
I suggest you include a license to let people know if/how/when they can use your code?
Good luck with your game!

**Comment by Dorthu** [comment]
Thanks for reaching out!  Tbh I hadn't considered including a license; I didn't think anyone would ever end up here 😅 I'll give it a look next time I'm at my desk.

Any license in particular you find useful for these kinds of projects?  I usually go three-clause bsd, but I'm not usually looking at licenses for projects with graphics.

**Comment by jay-jlm** [comment]
I like MIT as it's commercial re-use friendly, but definitely go with whichever one rocks your boat.
I have no experience with licenses, but I think you can just mention in the license file which parts the license applies to and which parts are not covered.
Here's an example from the Node.js license file:

> The Node.js license applies to all parts of Node.js that are not externally
> maintained libraries.
> The externally maintained libraries used by Node.js are:
